AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  calcRainWater

  Sample SAM Template for calcRainWater
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  CalcRainWaterFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: calc-rain-water/
      Handler: app.lambdaHandler
      Runtime: nodejs12.x
      Events:
        CalcRainWater:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /calc
            Method: get

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  CalcRainWaterApi:
    Description: "API Gateway endpoint URL for Prod stage for CalcRainWater function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/calc/"
  CalcRainWaterFunction:
    Description: "CalcRainWater Lambda Function ARN"
    Value: !GetAtt CalcRainWaterFunction.Arn
  CalcRainWaterFunctionIamRole:
    Description: "Implicit IAM Role created for CalcRainWater function"
    Value: !GetAtt CalcRainWaterFunctionRole.Arn
